### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by NicWhitham** [GlenioSP/Gutenberg-Search#1]
If anyone can assist me with the following issue, I would very much apprecdiate your help.  I am installing on Centos 8:

[root@localhost sb]# docker-compose up -d
Building gs-api
Step 1/17 : FROM python:3.7-alpine
3.7-alpine: Pulling from library/python
aad63a933944: Pull complete
f229563217f5: Pull complete
71ded8122394: Pull complete
807d0888ee2e: Pull complete
95206a02ba21: Pull complete
Digest: sha256:4a704ebee45695fa91125301e43eee08a85fc984d05cc75650cc66fad7826c56
Status: Downloaded newer image for python:3.7-alpine
 ---> 7fbc871584eb
Step 2/17 : RUN adduser -D gs
 ---> Running in 52aff84effeb
Removing intermediate container 52aff84effeb
 ---> 3c70bb2acdda
Step 3/17 : WORKDIR /home/gs
 ---> Running in f055e0f1e05b
Removing intermediate container f055e0f1e05b
 ---> 3d0bb25371bf
Step 4/17 : COPY requirements.txt requirements.txt
 ---> e7ee41877846
Step 5/17 : RUN python -m venv venv
 ---> Running in e7870d296574
Removing intermediate container e7870d296574
 ---> 0b6917516448
Step 6/17 : RUN venv/bin/pip install -r requirements.txt
 ---> Running in 4984bef4f6cf
Collecting certifi==2019.9.11 (from -r requirements.txt (line 1))
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f181bdd8210>: Failed to establish a new connection: [Errno -3] Try again')': /simple/certifi/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f181bd81d50>: Failed to establish a new connection: [Errno -3] Try again')': /simple/certifi/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f181bd8f050>: Failed to establish a new connection: [Errno -3] Try again')': /simple/certifi/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f181bd8f1d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/certifi/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f181bd8f190>: Failed to establish a new connection: [Errno -3] Try again')': /simple/certifi/
  ERROR: Could not find a version that satisfies the requirement certifi==2019.9.11 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for certifi==2019.9.11 (from -r requirements.txt (line 1))
ERROR: Service 'gs-api' failed to build: The command '/bin/sh -c venv/bin/pip install -r requirements.txt' returned a non-zero code: 1
[root@localhost sb]#

**Comment by GlenioSP** [comment]
Hi NicWhitham, 

I've updated the requirements file. Please try again. 
But looking for your docker logs, you're probably having connection issues to the Internet within docker or maybe only HTTPS connections.

**Comment by NicWhitham** [comment]
Thanks I will try again. Not sure why there may be any connection problems, everything else runs fine.  I will let you knowhow I get on.

Thanks once again - much appreciate your help.

**Comment by NicWhitham** [comment]
Similar issue - not sure why, I have tried disabling SELinux and Firewallbut still does not work:

[root@localhost sb]# docker-compose up -d
Building gs-api
Step 1/17 : FROM python:3.7-alpine
 ---> 7fbc871584eb
Step 2/17 : RUN adduser -D gs
 ---> Using cache
 ---> 939b2a4f7791
Step 3/17 : WORKDIR /home/gs
 ---> Using cache
 ---> 60983a331855
Step 4/17 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> b9cc09829c77
Step 5/17 : RUN python -m venv venv
 ---> Using cache
 ---> fadeecdfdfa4
Step 6/17 : RUN venv/bin/pip install -r requirements.txt
 ---> Running in fdee5472267c
Collecting Flask==1.1.1 (from -r requirements.txt (line 1))
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b1806c450>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b17e914d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b17e91490>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b17e916d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b17e918d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/flask/
  ERROR: Could not find a version that satisfies the requirement Flask==1.1.1 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for Flask==1.1.1 (from -r requirements.txt (line 1))
ERROR: Service 'gs-api' failed to build: The command '/bin/sh -c venv/bin/pip install -r requirements.txt' returned a non-zero code: 1
[root@localhost sb]#

**Comment by GlenioSP** [comment]
Hmm, maybe there is some proxy related issue? Did you try something like this? -> https://forums.docker.com/t/issue-with-installing-pip-packages-inside-a-docker-container-with-ubuntu/35107/3

**Comment by NicWhitham** [comment]
Thank you but I am not using a proxy

**Comment by NicWhitham** [comment]
I also tried to build it on my Windows 10 Docker instalation but get no response from localhost:


C:\Docker\sb>docker-compose up --build -d
Building gs-api
Step 1/17 : FROM python:3.7-alpine
3.7-alpine: Pulling from library/python
aad63a933944: Pull complete                                                                                                                                                                          f229563217f5: Pull complete                                                                                                                                                                          71ded8122394: Pull complete                                                                                                                                                                          807d0888ee2e: Pull complete                                                                                                                                                                          95206a02ba21: Pull complete                                                                                                                                                                          Digest: sha256:4a704ebee45695fa91125301e43eee08a85fc984d05cc75650cc66fad7826c56
Status: Downloaded newer image for python:3.7-alpine
 ---> 7fbc871584eb
Step 2/17 : RUN adduser -D gs
 ---> Running in f4d24c064df4
Removing intermediate container f4d24c064df4
 ---> 07bf250b620f
Step 3/17 : WORKDIR /home/gs
 ---> Running in 37d27bb9cfcf
Removing intermediate container 37d27bb9cfcf
 ---> 13e252ec4786
Step 4/17 : COPY requirements.txt requirements.txt
 ---> af789c008c8a
Step 5/17 : RUN python -m venv venv
 ---> Running in 1e2d1b0fc4b6
Removing intermediate container 1e2d1b0fc4b6
 ---> cf8a14f7e04b
Step 6/17 : RUN venv/bin/pip install -r requirements.txt
 ---> Running in 9b248e9663bc
Collecting Flask==1.1.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting Flask-Cors==3.0.8 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/78/38/e68b11daa5d613e3a91e4bf3da76c94ac9ee0d9cd515af9c1ab80d36f709/Flask_Cors-3.0.8-py2.py3-none-any.whl
Collecting elasticsearch==7.0.4 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/df/63/86cfe50a11621240450322509f8eacac14f3381cbf43aee2fe56db8c7c8a/elasticsearch-7.0.4-py2.py3-none-any.whl (83kB)
Collecting requests==2.23.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
Collecting Jinja2>=2.10.1 (from Flask==1.1.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl (126kB)
Collecting click>=5.1 (from Flask==1.1.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl (82kB)
Collecting Werkzeug>=0.15 (from Flask==1.1.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ba/a5/d6f8a6e71f15364d35678a4ec8a0186f980b3bd2545f40ad51dd26a87fb1/Werkzeug-1.0.0-py2.py3-none-any.whl (298kB)
Collecting itsdangerous>=0.24 (from Flask==1.1.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Six (from Flask-Cors==3.0.8->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting urllib3>=1.21.1 (from elasticsearch==7.0.4->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
Collecting certifi>=2017.4.17 (from requests==2.23.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
Collecting chardet<4,>=3.0.2 (from requests==2.23.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<3,>=2.5 (from requests==2.23.0->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->Flask==1.1.1->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Installing collected packages: MarkupSafe, Jinja2, click, Werkzeug, itsdangerous, Flask, Six, Flask-Cors, urllib3, elasticsearch, certifi, chardet, idna, requests
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
Successfully installed Flask-1.1.1 Flask-Cors-3.0.8 Jinja2-2.11.1 MarkupSafe-1.1.1 Six-1.14.0 Werkzeug-1.0.0 certifi-2019.11.28 chardet-3.0.4 click-7.1.1 elasticsearch-7.0.4 idna-2.9 itsdangerous-1.1.0 requests-2.23.0 urllib3-1.25.8
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 9b248e9663bc
 ---> 3359db3a1721
Step 7/17 : RUN venv/bin/pip install gunicorn
 ---> Running in b310a84bbae9
Collecting gunicorn
  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
Requirement already satisfied: setuptools>=3.0 in ./venv/lib/python3.7/site-packages (from gunicorn) (41.2.0)
Installing collected packages: gunicorn
Successfully installed gunicorn-20.0.4
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container b310a84bbae9
 ---> b96d82c42eaf
Step 8/17 : RUN apk --no-cache add curl
 ---> Running in 3cda0f8f0784
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/3) Installing nghttp2-libs (1.40.0-r0)
(2/3) Installing libcurl (7.67.0-r0)
(3/3) Installing curl (7.67.0-r0)
Executing busybox-1.31.1-r9.trigger
OK: 12 MiB in 37 packages
Removing intermediate container 3cda0f8f0784
 ---> 4e755c50c2ed
Step 9/17 : COPY app app
 ---> dfe2224c9bf2
Step 10/17 : COPY server.py config.py boot.sh wait-for.sh ./
 ---> 1bed89dba395
Step 11/17 : RUN chmod +x boot.sh
 ---> Running in ccd99457e603
Removing intermediate container ccd99457e603
 ---> 2d03c96f18c1
Step 12/17 : RUN chmod +x wait-for.sh
 ---> Running in bb9178e6ab15
Removing intermediate container bb9178e6ab15
 ---> 8729d76fc474
Step 13/17 : ENV FLASK_APP server.py
 ---> Running in c234f89fd756
Removing intermediate container c234f89fd756
 ---> 8d98db3c4e94
Step 14/17 : RUN chown -R gs:gs ./
 ---> Running in bfa17fbb9c29
Removing intermediate container bfa17fbb9c29
 ---> 70144d0a8980
Step 15/17 : USER gs
 ---> Running in ee223679dc77
Removing intermediate container ee223679dc77
 ---> 5d4642b21662
Step 16/17 : EXPOSE 5000
 ---> Running in ff1286119c4d
Removing intermediate container ff1286119c4d
 ---> 7d7702ded6f5
Step 17/17 : ENTRYPOINT ["./boot.sh"]
 ---> Running in 16c77ed3b70c
Removing intermediate container 16c77ed3b70c
 ---> a3601a670857

Successfully built a3601a670857
Successfully tagged sb_gs-api:latest
Building gs-ui
Step 1/12 : FROM node:12.2.0-alpine as build
12.2.0-alpine: Pulling from library/node
e7c96db7181b: Already exists                                                                                                                                                                         a9b145f64bbe: Pull complete                                                                                                                                                                          3bcb5e14be53: Pull complete                                                                                                                                                                          Digest: sha256:2ab3d9a1bac67c9b4202b774664adaa94d2f1e426d8d28e07bf8979df61c8694
Status: Downloaded newer image for node:12.2.0-alpine
 ---> f391dabf9dce
Step 2/12 : WORKDIR /app
 ---> Running in 9d7da6def4f5
Removing intermediate container 9d7da6def4f5
 ---> f97dc041f102
Step 3/12 : ENV PATH /app/node_modules/.bin:$PATH
 ---> Running in 1c41df6476e0
Removing intermediate container 1c41df6476e0
 ---> 1414ac933299
Step 4/12 : COPY package.json /app/package.json
 ---> 63faedc4d273
Step 5/12 : RUN npm install --silent
 ---> Running in 5ace323ab4fd
added 1619 packages from 773 contributors and audited 912869 packages in 107.289s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 5ace323ab4fd
 ---> 528815abc071
Step 6/12 : RUN npm install react-scripts@3.0.1 -g --silent
 ---> Running in 03e0cb7341ac
/usr/local/bin/react-scripts -> /usr/local/lib/node_modules/react-scripts/bin/react-scripts.js
+ react-scripts@3.0.1
added 1447 packages from 690 contributors in 150.786s
Removing intermediate container 03e0cb7341ac
 ---> d73dc5499d1a
Step 7/12 : COPY . /app
 ---> 3f2aa3b51741
Step 8/12 : RUN npm run build
 ---> Running in 672ccfbaaf0d

> ui@0.1.0 build /app
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  143.11 KB  build/static/js/2.bbca9158.chunk.js
  3.35 KB    build/static/js/main.7d99ed70.chunk.js
  769 B      build/static/js/runtime~main.821f54a4.js
  109 B      build/static/css/main.b6bc4ccb.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

Removing intermediate container 672ccfbaaf0d
 ---> c59812a774a2

Step 9/12 : FROM nginx:1.16.0-alpine
1.16.0-alpine: Pulling from library/nginx
Digest: sha256:270bea203d2fc3743fb9ce0193325e188b7e6233043487e3d3cf117ea4d3f337
Status: Downloaded newer image for nginx:1.16.0-alpine
 ---> ef04b00b089d
Step 10/12 : COPY --from=build /app/build /usr/share/nginx/html
 ---> Using cache
 ---> d6bf53dae946
Step 11/12 : EXPOSE 80
 ---> Using cache
 ---> ad6e5264f05e
Step 12/12 : CMD ["nginx", "-g", "daemon off;"]
 ---> Using cache
 ---> 28bec4adcb0f

Successfully built 28bec4adcb0f
Successfully tagged sb_gs-ui:latest
gs-ui is up-to-date
gs-elasticsearch is up-to-date
Creating gs-api ... done                                                                                                                                                                             
C:\Docker\sb>
C:\Docker\sb>
C:\Docker\sb>docker-compose ps
      Name                    Command               State   Ports
-----------------------------------------------------------------
gs-api             ./boot.sh                        Up
gs-elasticsearch   /usr/local/bin/docker-entr ...   Up
gs-ui              nginx -g daemon off;             Up

C:\Docker\sb>

**Comment by GlenioSP** [comment]
Well, I can't think of anything else right know why it isn't working on your linux machine. But I've created a dev branch with some modifications to work on Windows 10 (I need to test on Linux too). Please try this one and let me know.

**Comment by NicWhitham** [comment]
Thanks for that - things are looking much better, I now connect and I can see the search table page.  

I now need to work out how to load my local books as the windows version doesn't like the curl load book format.

**Comment by NicWhitham** [comment]
Having difficulty getting the books to load:

C:\Docker\sb-dev>curl -H "Content-Type: application/json" -X POST -d '{"book_url":"http://192.168.1.2/home/books/1001.txt"}' http://localhost:5000/books/load
{"error":"Bad Request","message":"400 Bad Request: The browser (or proxy) sent a request that this server could not understand."}

C:\Docker\sb-dev>

**Comment by GlenioSP** [comment]
If you can and want, download "Postman" for Windows and do the request there. It's a great tool. Besides, just pass the body => {"book_url":"https://www.gutenberg.org/files/1342/1342-0.txt"} to your request, it'll download the book directly from gutenberg website.

**Comment by NicWhitham** [comment]
let me give it a try

**Comment by NicWhitham** [comment]
There was a syntax error in my original import line which I corrected and managed to load all my books via curl in the cmd shell and I needed to escape some double quotes, like this:

curl -H "Content-Type: application/json" -X POST -d {"\"book_url\":\"http://192.168.1.2/home/books/1001.txt\"}" http://localhost:5000/books/load


Thanks for your help - much appreciated

**Comment by GlenioSP** [comment]
Great, you're welcome.

**Comment by NicWhitham** [comment]
This is working extremely well on my local Windows PC but I can't seem to be able to workout how to access it from another PC on the same internal network. Any pointers would bemuch appreciated.

**Comment by NicWhitham** [comment]
I have tried routing ports and other things but can not access this across my network, the user interface comes up with out a problem but unable to search.  I even tried on Rasberry Pi4 but the gs-elasticsearch keeps crashing. I will have to revert back to Linux I think. Please can you tell me which distro of linux you are using - that may solve my issues.  Many thanks

**Comment by GlenioSP** [comment]
Sorry, I couldn't answer you before. I've tested the application on Linux Ubuntu (version 18+) and Mint (version 19+). I remember something related to elasticsearch crashes, maybe related to docker-compose working on a network mode different from 'host'. When I've created the dev branch using the bridge mode in docker-compose, it worked on Windows but maybe crashed elasticsearch in this case you have exposed. I can confirm it now. When I got some time, I'll give it a try to understand what is happening. Meanwhile, please try running the application on the distros I told you and using the 'master' branch for it.

**Comment by NicWhitham** [comment]
I have successfully built a Mint distro machine and successfully installed master-dev and uploaded books. I can use it locally and everything works well.  However, it does not work on remote PC’s unless they have docker-compose and the same package up and running locally.  I am not sure what it needs access to locally or how to get that from the remote PC.

**Comment by GlenioSP** [comment]
Sorry, I'm late. Anyway, I've done some modifications. The master branch is up to date. Please, give it a try and let me know if it's working now.

**Comment by NicWhitham** [comment]
I have installed it on my Mint Linux PC and it built fine but not able to load books.  I have tried changing localhost with actual ip, tried escaping the quotes and I constantly get the following error:

# curl --header "Content-Type: application/json" --request POST --data '{"book_url":"http://192.168.1.2/home/books/1001fix.txt"}' http://localhost:5000/books/load
{"error":"Not Found","message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

The url is correct, if I enter in browser it displays the text file.  I tried changing localhost in  http://localhost:5000/books/load to actual ip of Mint PC, but nothing seems to allow me to load the books (thjis part does work in Docker for Windows).

**Comment by GlenioSP** [comment]
Minor fix. I forgot to update the README file. The API endpoint it's now: http://localhost:5000/api/books/load.

**Comment by NicWhitham** [comment]
Thanks I managed to upload them correctly.  Now I ned to work out how to password protect it when accessing from outside the network.

**Comment by GlenioSP** [comment]
That's a good side project. Maybe you could do a future PR of this feature? 
Anyway, I'm closing this issue now. Thanks for contributing to this project.
