### ISSUE TITLE
Next page issues

### ISSUE THREAD

**Issue by NicWhitham** [GlenioSP/Gutenberg-Search#2]
It would seem the pagination is not working in the updated release.  Next throws an error:

404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Thanks

**Comment by NicWhitham** [comment]
Any idea when you may be a ble to look at the pagination issue?

**Comment by GlenioSP** [comment]
I haven't got much time these days, but I've just updated the code. Please give it a try.

**Comment by NicWhitham** [comment]
Seems to be working fine

**Comment by GlenioSP** [comment]
Good. Thank you for your contributions. Closing the issue now.
